# Generated by Django 3.0.7 on 2023-02-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseBillDetails',
            new_name='PurchaseBillDetail',
        ),
        migrations.RenameModel(
            old_name='SaleBillDetails',
            new_name='SaleBillDetail',
        ),
    ]
